#! /bin/bash
# Do not edit this file; it's generated by ./build_apt-get.sh.
# Any manual changes will be overwritten.
sudo apt-get install --assume-yes containerd.io curl docker-buildx-plugin docker-ce docker-ce-cli docker-compose-plugin htop python3-pip python3-venv
